### ISSUE TITLE
Eliminate error message: No TV libraries are configured in Emby Library setup

### ISSUE THREAD

**Issue by LukePulverenti** [MediaBrowser/Emby.AutoOrganize#19]
This validation should still take place, but only at the point of attempting to create a new series. It should not prevent the user from selecting an existing series using the drop down.

**Comment by PoppyPop** [comment]
I tried hard to reproduce with no success, i got the message "No TV libraries are configured in Emby library setup." only when i click on the "+" next to the dropdown list.

When i simply identify an item, all is working correctly.

Can you give me more details, or steps to reproduce ?

**Comment by andy29485** [comment]
I'm not sure about reproducing, but I found a workaround.
1. Click the folder icon near an unidentified (red) episode
    - selecting the `+` icon bring about that error
    - attempting to use the `Series` drop-down results in no option
2. Change `Media Type` from `Series` to `Movie`
3. Change `Media Type` back to `Series`
4. It works as expected

Note: after step 2, wait out the loading circle, otherwise Movies will appear (at step 4) in the drop-down even if `Series` is selected

**Comment by PoppyPop** [comment]
Can you give me plugin version and server version ?
I think it's the same problem as #4 and #6

**Comment by Mogub** [comment]
Same problem here, and yes, got the same problem as #4 and #6 and #19.  No automatic filling, no TV Series in the combobox. Have to do the andy29485 trick everytime I need to create a new serie or assign one manually.

Emby Version 3.5.2.0
Auto-Organize version 1.2.8.0

**Comment by PoppyPop** [comment]
Could you give me some information on your library setup ?
- Multiple series library ?
- Multiple folders ?
- Wich option selected (in advanced mode)
- Platform (windows, unix, syno, ...)

**Comment by Mogub** [comment]
![emby 1](https://user-images.githubusercontent.com/42151874/43919602-6ad6032e-9be4-11e8-9aa0-4da1e248c58e.JPG)

See Screenshot for library information.
Multiple series libraries, multiple folders.
Advanced mode (where)?????
Platform : Windows

**Comment by cirolaferrara** [comment]
Same here. In addition I have:
`2018-09-17 10:39:09.030 Info HttpServer: HTTP POST http://_myserver_.zapto.org:8096/emby/Library/FileOrganizations/cc794c111a5f18c4c176f784dfab3a46/Episode/Organize. UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
2018-09-17 10:39:09.032 Warn App: No provider metadata found for _myseries_ episode 5
2018-09-17 10:39:09.033 Error HttpServer: Error processing request
        *** Error Report ***
        Version: 3.5.2.0
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby-server -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
        Operating system: Unix 4.13.0.46
        64-Bit OS: True
        64-Bit Process: True
        User Interactive: True
        Processor count: 8
        Program data path: /var/lib/emby-server
        Application directory: /opt/emby-server/system
        System.Exception: No provider metadata found for _myseries_ episode 5
           at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(EpisodeFileOrganizationRequest request)
        System.Exception
           at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(EpisodeFileOrganizationRequest request)

2018-09-17 10:39:09.033 Info HttpServer: HTTP Response 500 to ip. Time: 4ms. http://_myserver_.zapto.org:8096/emby/Library/FileOrganizations/cc794c111a5f18c4c176f784dfab3a46/Episode/Organize
`
