### ISSUE TITLE
AutoOrganize not working with Emby 4.2.0.40

### ISSUE THREAD

**Issue by jankete** [MediaBrowser/Emby.AutoOrganize#32]
Hi, since the Update for Emby to version 4.2.0.40 AutoOrganize doesn't work anymore. Here is what I found in de logs:

```2019-08-01 07:13:31.941 Info HttpClient: GET https://www.thetvdb.com/api/B89CE93890E9419B/series/311902/all/de.zip
2019-08-01 07:13:32.556 Info HttpClient: GET https://www.thetvdb.com/api/B89CE93890E9419B/series/311902/all/en.zip
2019-08-01 07:13:33.043 Error ProviderManager: Error searching
	*** Error Report ***
	Version: 4.2.0.40
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.55
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: NotFound
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Tvdb.TvdbSeriesProvider.DownloadSeriesZip(String seriesId, String idType, String seriesName, Nullable`1 seriesYear, String seriesDataPath, Nullable`1 lastTvDbUpdateTime, String preferredMetadataLanguage, String saveAsMetadataLanguage, CancellationToken cancellationToken)
	   at Tvdb.TvdbSeriesProvider.DownloadSeriesZip(String seriesId, String idType, String seriesName, Nullable`1 seriesYear, String seriesDataPath, Nullable`1 lastTvDbUpdateTime, String preferredMetadataLanguage, CancellationToken cancellationToken)
	   at Tvdb.TvdbSeriesProvider.EnsureSeriesInfo(Dictionary`2 seriesProviderIds, String seriesName, Nullable`1 seriesYear, String preferredMetadataLanguage, CancellationToken cancellationToken)
	   at Tvdb.TvdbEpisodeProvider.GetSearchResults(EpisodeInfo searchInfo, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()
	
2019-08-01 07:13:33.064 Info HttpClient: GET https://private.omdbapi.com?apikey=fe53f97e&plot=full&r=json&i=tt1399045&Episode=1&Season=3
2019-08-01 07:13:33.208 Info HttpClient: GET https://api.themoviedb.org/3/tv/67133/season/3/episode/1?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=images,external_ids,credits,videos&language=de&include_image_language=de,null,en
2019-08-01 07:13:33.844 Warn App: No provider metadata found for MacGyver (2016) season 3 episode 1
2019-08-01 07:13:33.850 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.2.0.40
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.55
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 4
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.Exception: System.Exception: No provider metadata found for MacGyver (2016) season 3 episode 1
	   at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(EpisodeFileOrganizationRequest request)
	Source: Emby.AutoOrganize
	TargetSite: Void MoveNext()```

**Comment by LukePulverenti** [comment]
https://emby.media/community/index.php?/topic/58523-tvdb-changes/

**Comment by jankete** [comment]
As it seems to be a problem with TheTVDB and not with AutoOrganize, the issue can be closed.
